var CPWbot_cs;CPWbot_cs||(CPWbot_cs=new CPWbot_cs_lib);
function CPWbot_cs_lib(){this.JSON=JSON;JSON||(this.JSON=LPJSON);this.alert=alert;this.fill_field=function(a,b){a||(a=LP_derive_doc());if(!b||!a)return!1;var c=0,d=this.getElementByType(a,b);d?g_isfirefox?this.alert("TODO"):(verbose_log("filling element ty="+b.id_type+" val="+b.id_value),d.focus(),d.value=b.field_value,fire_onchange(d),c=1):verbose_log("unable to find element ty="+b.id_type+" val="+b.id_value);sendBG({cmd:"cpwbot_fill_ack",url:a.location.href,docstate:a.readyState,id_type:b.id_type,
id_value:b.id_value,found:c?1:0});return!0};this.click_field=function(a,b){a||(a=LP_derive_doc());if(!b||!a)return!1;var c=this.getElementByType(a,b),d=0;c?(verbose_log("[docnum:"+g_docnum+"][state:"+b.pwchangestate+"] clicking element ty="+b.id_type+" val="+b.id_value),this.do_click(a,c),d=1):verbose_log("[docnum:"+g_docnum+"][state:"+b.pwchangestate+"] unable to find element in this frame to click : ty="+b.id_type+" val="+b.id_value);g_isfirefox?alert("TODO"):sendBG({cmd:"cpwbot_click_ack",url:a.location.href,
docstate:a.readyState,pwchangestate:b.pwchangestate,msgid:b.msgid,id_type:b.id_type,id_value:b.id_value,found:d?1:0})};this.clear_field=function(a,b){a||(a=LP_derive_doc());return!b||!a?!1:!0};this.execute_script=function(a,b){a||(a=LP_derive_doc());if(!b||!a)return!1;var c=b.js;c&&(verbose_log("["+g_docnum+"] executing JS: "+c),c="try{"+c+"}catch(e) {}",g_isfirefox?(this.alert("TODO"),pass):run_custom_js(a,c));return!0};this.getElementByType=function(a,b){a||(a=LP_derive_doc());if(!b||!a)return null;
var c=null,d=null,d=b.id_type,h=b.id_value,f=666;if(d&&h)switch(d){case "id":c=a.getElementById(h);break;case "name":(d=a.getElementsByName(h))&&0<d.length&&(c=d[0]);break;case "xpath":g_isie&&"undefined"!=typeof init_LPfn&&(init_LPfn()&&LPfn)&&(f=LPfn.getDocumentMode(a));8>f?alert("old IE - does not bundle in XPATH support. TODO "):c=LP_getElementByXPath(a,h);break;default:pass}return c};this.getElementsByType=function(a,b){a||(a=LP_derive_doc());if(!b||!a)return null;var c=null,d=[],h=b.type,f=
b.val,j=666;if(h&&f)switch(h){case "id":(c=a.getElementById(f))&&d.push(c);break;case "name":a.getElementsByName(f);break;case "xpath":g_isie&&"undefined"!=typeof init_LPfn&&(init_LPfn()&&LPfn)&&(j=LPfn.getDocumentMode(a));8>j?this.alert("old IE - does not bundle in XPATH support. TODO "):LP_getElementsByXPath(a,f);break;default:pass}return c};this.click_submit_field=function(a,b){a||(a=LP_derive_doc());return!b||!a?null:!0};this.field_is_displayed=function(a,b){a||(a=LP_derive_doc());return!b||!a?
!1:lpIsVisible(a,b)&&is_wacky_disp(a,b)?!0:!1};this.do_click=function(a,b){a||(a=LP_derive_doc());if(!b||!a||!this.field_is_displayed(a,b))return!1;b.focus();g_isfirefox?fireEvent(b,"click","MouseEvents"):LP_fireEvent(b,"click","MouseEvents");return!0};this.decode_fields_metainfo=function(a){var b="";a&&(b=this.JSON.parse(a));return b};this.validate_page_fields=function(a,b,c,d,h,f,j){if(!a)return null;h=!0;var e={};verbose_log("running validate_page_fields in frame "+g_docnum+" for "+b);c||(c=[]);
d||(d=[]);b=!1;var n=0,g=0,l=0,k;if(f){k=RegExp(f,"i");var m=punycode.URLToASCII(a.location.href);if(k.exec(m))return e.num_ok_matches=null,e.num_okfields=null,e.found_bad_match=null,e.num_badfields=null,e.url_success_match=!0,e.url_failure_match=!1,e.do_retry=!1,e.retval=!0,L("["+g_docnum+"] returning true, matched success url "+f),e}if(j&&(k=RegExp(j,"i"),m=punycode.URLToASCII(a.location.href),k.exec(m)))return e.num_ok_matches=null,e.num_okfields=null,e.found_bad_match=null,e.num_badfields=null,
e.url_failure_match=!0,e.url_success_match=!1,e.do_retry=!1,e.retval=!1,L("["+g_docnum+"] returning false, matched failure url "+j),e;for(f=0;f<c.length;f++)if(k=c[f].id_type,j=c[f].id_value,k=this.getElementByType(a,{id_type:k,id_value:j}))n++,g++;else{verbose_log("["+g_docnum+"] DID NOT FIND REQUIRED FIELD "+j);break}g<c.length&&(b=!0,h=null);if(h)for(f=0;f<d.length;f++)if(k=d[f].id_type,j=d[f].id_value,k=this.getElementByType(a,{id_type:k,id_value:j})){n++;l=1;verbose_log("["+g_docnum+"] FOUND REJECT FIELD "+
j);b=h=!1;break}else b=!0;if(0===n&&(0<c.length||0<d.length))h=null;e&&(e.num_ok_matches=g,e.num_okfields=c.length,e.found_bad_match=l,e.num_badfields=d.length,e.do_retry=b,e.retval=h,e.url_success_match=!1,e.url_failure_match=!1);return e};this.interrogate=function(a,b,c){if(b&&!(10<c)){var d=b.desc;"undefined"==typeof c&&(c=1);"complete"!=a.readyState?(verbose_log("["+g_docnum+"] retry "+d+" in 500ms doc state is "+a.readyState),setTimeout(function(){CPWbot_cs.interrogate(a,b,c+1)},500)):g_cpwbot&&
CPWbot_cs&&CPWbot_cs.interrogate_validate(a,b)}};this.interrogate_validate=function(a,b,c){if(!b||10<c)return!1;if("undefined"==typeof c||null===c)c=1;var d=b.desc,h=b.required_fields,f=b.rejected_fields,j=b.required_url,e=b.rejected_url,n=b.id,g=b.validate_timeout,l=b.timestamp,l=((new Date).getTime()-l)/1E3;if("undefined"==typeof g||null===g)g=0;if(0<g&&c>=g/2E3)return L("terminate loop  ["+g_docnum+"] VT:"+g+" T:1000 ctr"+c+" elapsed time is "+l+" sec"),!1;L("WTF??  ["+g_docnum+"] VT:"+g+" T:1000 ctr"+
c+" elapsed time is "+l+" sec");var k=CPWbot_cs.decode_fields_metainfo(h),m=CPWbot_cs.decode_fields_metainfo(f);if(0===k.length&&0===m.length&&!e&&!j)return verbose_log("["+g_docnum+"] warning: interrogate rcvd no inputs or urls to check against"),g=!0,sendBG({cmd:"cpwbot_validate_state_result",state:"STATE"+c,url:a.location.href,docstate:a.readyState,desc:d,id:n,required_fields:h,rejected_fields:f,required_url:j,rejected_url:e,result_obj:CPWbot_cs.JSON.stringify(p),result:CPWbot_cs.JSON.stringify(g)}),
!0;var p=CPWbot_cs.validate_page_fields(a,d,k,m,g,j,e);if(null===p)return null;g=p.retval;p.do_retry&&null===g?(verbose_log("["+g_docnum+"] ctr="+c+" elapsed="+l+" sec, validate_page_fields "+d+" retry in 1 second"),setTimeout(function(){var g=CPWbot_cs.interrogate_validate(a,b,c+1);g||(g=0===k.length&&0<m.length||0<k.length&&0<m.length&&0<p.num_ok_matches?!0:!1,g_isfirefox?pass:sendBG({cmd:"cpwbot_validate_state_result",state:"STATE_TIMEDOUT",url:a.location.href,docstate:a.readyState,desc:d,id:n,
required_fields:h,rejected_fields:f,required_url:j,rejected_url:e,result_obj:CPWbot_cs.JSON.stringify(p),result:CPWbot_cs.JSON.stringify(g)}))},1E3)):(null===g&&(verbose_log("["+g_docnum+"] cpwbot_validate_state_result retval===null FIXME"),g=!1),g_isfirefox?pass:sendBG({cmd:"cpwbot_validate_state_result",state:"STATE"+c,url:a.location.href,docstate:a.readyState,desc:d,id:n,required_fields:h,rejected_fields:f,required_url:j,rejected_url:e,result_obj:CPWbot_cs.JSON.stringify(p),result:CPWbot_cs.JSON.stringify(g)}));
return!0};return!0}
function display_cpw_message(a,b){if(a){var c=a.createElement("div");c.style.width="100%";c.style.height=window.innerHeight+"px";c.style.opacity="0.7";c.style.backgroundColor="#666666";c.id="cpwbg";c.style.position="absolute";c.style.top="0px";c.style.left="0px";a.body.appendChild(c);var d=a.createElement("div");d.id="cpwmsg";d.style.top="100px";d.style.left="100px";d.style.position="absolute";c.appendChild(d);d.style.backgroundColor="white";d.style.color="black";d.style.fontSize="40px";g_isfirefox?
d.textContent=b:d.innerText=b}}function cpw_hide_overlay(a){if(!a)return!1;(a=a.getElementById("lpiframeoverlaycpwmsg"))&&a.parentNode.removeChild(a);return!0}function do_cpw_overlay_handler(a){if(CPWbot_cs&&CPWbot_cs.JSON&&a.msg){var b=CPWbot_cs.JSON.parse(a.msg);b?(b=encodeURIComponent(b.msg),verbose_log("show overlay msg="+b),showoverlay(a,"&cpwbot="+b)):verbose_log("failure, !msg")}};
