var KEY_UP=38,KEY_DOWN=40,KEY_ENTER=13,ELEMENT_NODE=1,KEY_ESCAPE=27,KEY_F4=115,KEY_LEFT=37,KEY_RIGHT=39,KEY_HOME=36,KEY_END=35,g_do_complete=!0,g_do_svg=!0;function openCombo(a,c,b,d){d=d?d:document;a=d.getElementById(c);a.disabled||(b=gComboEx=d.getElementById(b),"block"!=b.style.display?showCombo(a,b,null,d):setStyle(b,"display","none",""),gItemNum=-1,gFocusItem=a,("undefined"!=typeof window?window:d.defaultView).setTimeout(function(){doFocus()},0))}
var g_iField=null,g_cb=null,g_combobox_button=null;function showCombo(a,c,b,d){d=d?d:document;g_iField=a;g_cb=c;null!=a&&(c=getComboButtonId(a.id),g_combobox_button=d.getElementById(c),"undefined"!=typeof a.addEventListener?a.addEventListener("move",function(){realShowCombo(d)},!1):a.attachEvent("onmove",function(){realShowCombo(d)}));realShowCombo(d)}function getY(a){for(var c=0;null!=a;)c+=a.offsetTop,a=a.offsetParent;return c}
function getX(a){for(var c=0;null!=a;)c+=a.offsetLeft,a=a.offsetParent;return c}
function realShowCombo(a){null==a&&(a=document);var c=getY(g_iField),b=getX(g_iField),c=c+g_iField.offsetHeight+"px",b=b+"px";g_cb.style.minWidth=g_iField.offsetWidth-14+"px";setStyle(g_cb,"top",c,"");setStyle(g_cb,"left",b,"");setStyle(g_cb,"display","block","");g_combobox_button&&setStyle(g_combobox_button,"display","","");b=LP_getAbsolutePos(a,g_iField);null!=b&&0<b.left&&(a="undefined"!=typeof window&&"undefined"!=typeof window.setTimeout?window:a.defaultView,c=a.innerWidth,null==c&&"undefined"!=
typeof getWindowWidth&&(c=getWindowWidth(a)),null!=c&&0<c&&(g_cb.style.maxWidth=parseInt(c)-parseInt(b.left)-16+"px",parseInt(g_cb.style.maxWidth)<parseInt(g_cb.style.minWidth)&&(g_cb.style.minWidth=g_cb.style.maxWidth)))}var gItemNum=0,gComboEx=null;
function focusCombo(a,c,b){var d="undefined"!=typeof document?document:a.view.document;a=a.keyCode;var e=!0;b=gComboEx=d.getElementById(b);if(a==KEY_DOWN||a==KEY_F4){e=!1;"block"!=b.getAttribute("style.display")&&showCombo(c,b,null,d);c=b.childNodes;d=c.length;for(b=0;null!=c[b]&&b<d;){if(c[b].nodeType==ELEMENT_NODE&&"item"==c[b].className&&"none"!=c[b].style.display){gFocusItem=c[b];break}b++}gItemNum=b;b>=d&&(gItemNum=0);setTimeout(function(){doFocus()},0);e=!1}else a!=KEY_ENTER&&a==KEY_ESCAPE&&
(null!=c.val&&0<c.val.length?e=!0:(e=!1,setStyle(gComboEx,"display","none",""),gItemNum=-1));return e}
function focusItem(a,c,b){a=b.val;for(var d=null,e=getItems(c),k=e.length,h=!1,m=0;m<k;m++)if(e[m].hasChildNodes()&&e[m].firstChild.nodeValue==a){h=!0;d=e[m];gItemNum=m;break}h||(d=addItem(c,a,e.length),gItemNum=e.length);null!=d&&(gFocusItem=d,"block"!=gComboEx.getAttribute("style.display")?(a=b.offsetLeft+"px",setStyle(c,"top",b.offsetTop+b.offsetHeight+"px",""),setStyle(c,"left",a,"")):setStyle(c,"display","none",""),setStyle(c,"display","block",""),setTimeout(function(){doFocus()},0))}
function addItem(a,c,b,d){d||(d=document);var e=d.createElement("div"),k="undefined"!=typeof c.label?c.label:c;e.val="undefined"!=typeof c.label?c.value:c;e.label=k;if("undefined"!=typeof c.label&&(e.label=c.label,"undefined"!=typeof c.image)){var h=d.createElement("img");h.src=c.image;h.style.paddingRight="15px";e.appendChild(h);e.img=h.src}c=d.createTextNode(k);e.appendChild(c);e.setAttribute("tabindex","-1");e.setAttribute("class","item");e.setAttribute("data-lpcount",b);"undefined"!=typeof e.addEventListener?
(e.addEventListener("click",function(){gItemNum=this.getAttribute("data-lpcount")}),e.addEventListener("mouseover",function(){gFocusItem=this;doFocus()})):(e.attachEvent("onclick",function(){gItemNum=this.getAttribute("data-lpcount")}),e.attachEvent("onmouseover",function(){gFocusItem=this;doFocus()}));e.setAttribute("role","listitem");e.setAttribute("origText",ofa(k));a.appendChild(e);return e}
function doComboNav(a,c,b,d){var e=a.keyCode,k=!0;null==gComboEx&&(gComboEx=c);if(e==KEY_UP||e==KEY_DOWN){k=!1;a=0;c=getItems(gComboEx);var h=c.length;if(e==KEY_UP)for(a=gItemNum-1;0<=a&&"none"==c[a].style.display;)"none"==c[a].style.display&&a--;else{a=gItemNum+1;for(a==h&&(a=-1);0<=a&&a<h&&"none"==c[a].style.display;)"none"==c[a].style.display&&a++;a==h&&(a=-1)}gItemNum=a;gFocusItem=-1==gItemNum?d.getElementById(b):c[a];setTimeout(function(){doFocus()},0)}else if(e==KEY_ENTER||!a.keyCode&&0<=a.button){if(c=
getItems(gComboEx),e=c[gItemNum],null!=e&&"true"!=e.getAttribute("aria-disabled")){a=e.label;c=e.val;b=d.getElementById(b);b.value=a;b.val=c;"undefined"!=typeof e.img&&(b.style.background="url("+e.img+") no-repeat 2px 5px",b.style.paddingLeft="25px");if(b.onchange)b.onchange();setStyle(gComboEx,"display","none","");gItemNum=0;gFocusItem=b;setTimeout(function(){doFocus()},0)}}else e==KEY_ESCAPE&&(k=!1,setStyle(c,"display","none",""),gItemNum=0,gFocusItem=d.getElementById(b),setTimeout(function(){doFocus()},
0));return k}function getItems(a){if(null===a)return[];var c=[],c=[];a=a.childNodes;for(var b=a.length,d=0;d<b;d++)if(a[d].nodeType==ELEMENT_NODE&&("item"==a[d].getAttribute("class")||"item focus"==a[d].getAttribute("class")))c[c.length]=a[d];return c}
function setStyle(a,c,b,d){var e=!1;try{a.style&&a.style.setProperty&&(a.style.setProperty(c,b,d),e=!0)}catch(k){alert("exception caught setting style: "+k.message)}if(!e)try{a.style[c]=b,e=!0}catch(h){alert("exception caught setting direct style: "+h.message)}return e}var gFocusItem=null,gLastFocusItem=null;
function doFocus(){null!=gFocusItem&&(gFocusItem.focus(),gLastFocusItem&&"item focus"==gLastFocusItem.className&&(gLastFocusItem.className="item"),gFocusItem&&"item"==gFocusItem.className&&(gFocusItem.className="item focus"),gLastFocusItem=gFocusItem,gFocusItem=null)}
function create_combo(a,c,b,d,e,k,h,m,l){d||(d=document);e||(e="");var f=d.getElementById(a),r=getComboId(a);if(!(d.getElementById(r)||null===r)){f.onkeydown=function(a){return focusCombo(a,f,r)};f.onkeyup=function(a){keyupCombo(d,a,f,r);return!1};f.setAttribute("role","textfield");f.setAttribute("aria-haspopup","true");f.setAttribute("autocomplete","off");f.style.marginRight="0px";var g=d.createElement(e+"div");g.setAttribute("role","list");g.style.display="none";"undefined"!=typeof g_isie&&g_isie&&
(g.style.display="none");g.setAttribute("id",r);g.setAttribute("class","dropStyle");"undefined"!=typeof g_isie&&g_isie&&(g.className="dropStyle");g.onkeydown=function(a){return doComboNav(a,this,this.id.substring(0,this.id.length-6),d)};"undefined"!=typeof g.addEventListener?g.addEventListener("click",function(a){doComboNav(a,this,this.id.substring(0,this.id.length-6),d)}):g.attachEvent("onclick",function(a){doComboNav(a,this,this.id.substring(0,this.id.length-6),d)});g.style.overflowY="auto";g.style.overflowX=
"auto";"undefined"!=typeof g_isie&&g_isie&&(g.style.background="#fff");g.style.paddingLeft="6px";g.style.paddingRight="6px";g.style.position="absolute";g.setAttribute("autofilled","false");l?insertAfter(d.getElementById(l),g):"undefined"!=typeof d.body&&d.body?d.body.appendChild(g):f.parentNode.parentNode.appendChild(g);"undefined"!=typeof f.ownerDocument.defaultView&&"undefined"!=typeof f.ownerDocument.defaultView.addEventListener?(f.ownerDocument.defaultView.addEventListener("click",function(b){b.target.id!=
a&&close_combo(a,d)},!1),f.addEventListener("keydown",function(b){9==b.keyCode&&close_combo(a,d)},!1)):(document.attachEvent("onclick",function(){window.event.srcElement.id!=a&&close_combo(a,d)}),document.attachEvent("onkeydown",function(b){9==b.keyCode&&close_combo(a,d)}));for(l=0;l<c.length;l++)addItem(g,c[l],l,d);c=("undefined"==typeof gLocalBaseUrl?"":gLocalBaseUrl)+"images/pwdrop.png";g_do_svg&&(c=("undefined"==typeof gLocalBaseUrl?"":gLocalBaseUrl)+"images/teardrop.png");if("undefined"!=typeof g_isie&&
g_isie||"undefined"!=typeof g_isfirefox&&g_isfirefox)c="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAfElEQVQ4T2NkoDJgpLJ5DKMGUh6io2GIGobe3t4LGBkZ49FD9v///wu3bt2agC3ECYYhuqH4DANZQNDAgIAAgT9//hwAqtUH4ossLCwOGzZs+IArPRA0EKQRZOjv378nsLKyFuAzjCgXkpoyiXIhKYaOGkhKaGFXS/UwBABG2SEVsoLJ9AAAAABJRU5ErkJggg==";if(b&&"undefined"!=typeof LP_getAbsolutePos){var s=0,p=0,g=d.createElement(e+"div");"undefined"!=typeof d.body&&d.body?k?insertAfter(d.getElementById(k),g):d.body.appendChild(g):
f.parentNode.appendChild(g);var j=getComboButtonId(a);b=[];var q=3,u;u="undefined"!=typeof f.ownerDocument.defaultView&&"undefined"!=typeof f.ownerDocument.defaultView.getComputedStyle?f.ownerDocument.defaultView.getComputedStyle(f):f.currentStyle;e=LP_getAbsolutePos(d,f);if(null!=e&&0<e.left&&0<e.top){var t;t=e.left+parseInt(e.width)+4-30;p=s=0;"undefined"!=typeof g_isie&&g_isie&&(p=-4,s=2);b.left=t+p+"px";b.position="absolute";b.top=parseInt(e.top)+4+s+"px";if("undefined"==typeof g_isfirefox||!g_isfirefox)b.padding=
q+"px"}var n=Math.floor((30-e.height)/2);if(1<=n&&30>e.height&&(p=s=0,b=[],b.position="absolute",b.height=e.height-4+"px",b.width=e.height-4+"px",b.top=parseInt(e.top)+4+n+4+"px",t=e.left+parseInt(e.width)+4-30+n+4,b.left=t+n+"px",q-=2*n,0>q&&(q=0),"undefined"==typeof g_isfirefox||!g_isfirefox))b.padding=q+"px";n=Math.round((e.height-30)/2);if(30<e.height&&(p=s=0,"undefined"!=typeof g_isie&&g_isie&&(b=parseInt(u.borderTopWidth),p=parseInt(u.borderBottomWidth),n-=(b+p)/2,p=-5,s=b),b=[],b.left=t+p+
"px",b.position="absolute",b.top=e.top+n+s+"px",q+=2*n,"undefined"==typeof g_isfirefox||!g_isfirefox))b.padding=q+"px";"undefined"!=typeof g_isie&&g_isie&&(b.border="0px");f.style.textOverflow="ellipsis";f.style.whiteSpace="nowrap";k&&(g.style.marginLeft=h?h+"px":"-15px",g.style.display="inline",g.style.verticalAlign="top",g.style.marginTop="6px",m?(b=[],b.marginTop=m+"px"):b.marginTop="-18px");k="<img id='"+j+"' src='"+c+"' valign='middle'/>";g.innerHTML="undefined"!=typeof g_isfirefox&&g_isfirefox?
xulize(k):k;j=d.getElementById(j);for(l in b)b.hasOwnProperty(l)&&(j.style[l]=b[l]);j.onclick=function(a){openCombo(a,this.id.substring(0,this.id.length-7),getComboId(this.id.substring(0,this.id.length-7)),d);null!=a?a.cancelBubble=!0:window.event.cancelBubble=!0};"undefined"!=typeof g_isie&&g_isie||"undefined"!=typeof g_isfirefox&&g_isfirefox||j.setAttribute("onerror","this.removeAttribute('onerror'); this.src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAfElEQVQ4T2NkoDJgpLJ5DKMGUh6io2GIGobe3t4LGBkZ49FD9v///wu3bt2agC3ECYYhuqH4DANZQNDAgIAAgT9//hwAqtUH4ossLCwOGzZs+IArPRA0EKQRZOjv378nsLKyFuAzjCgXkpoyiXIhKYaOGkhKaGFXS/UwBABG2SEVsoLJ9AAAAABJRU5ErkJggg==';")}else!b&&
"undefined"!=typeof LP_getAbsolutePos&&(j=d.createElement(e+"img"),j.id=getComboButtonId(a),null!==j.id&&(j.onclick=function(a){openCombo(a,this.id.substring(0,this.id.length-7),getComboId(this.id.substring(0,this.id.length-7)),d);null!=a?a.cancelBubble=!0:window.event.cancelBubble=!0}),"undefined"!=typeof g_isie&&g_isie||"undefined"!=typeof g_isfirefox&&g_isfirefox||j.setAttribute("onerror","this.removeAttribute('onerror'); this.src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAfElEQVQ4T2NkoDJgpLJ5DKMGUh6io2GIGobe3t4LGBkZ49FD9v///wu3bt2agC3ECYYhuqH4DANZQNDAgIAAgT9//hwAqtUH4ossLCwOGzZs+IArPRA0EKQRZOjv378nsLKyFuAzjCgXkpoyiXIhKYaOGkhKaGFXS/UwBABG2SEVsoLJ9AAAAABJRU5ErkJggg==';"),
j.setAttribute("src",c),j.setAttribute("valign","middle"),"undefined"!=typeof g_isopera&&g_isopera&&(j.style.position="relative",j.style.top="7px"),"undefined"!=typeof d.body&&d.body?d.body.appendChild(j):d.getElementById("main").appendChild(j),e=LP_getAbsolutePos(d,f),null!=e&&(0<e.left&&0<e.top)&&(t=e.left+e.width+2,j.style.left=t+"px",j.style.position="absolute",j.style.top=e.top+"px"),n=Math.floor((30-e.height)/2),1<=n&&30>e.height&&(j.style.height=e.height+"px",j.style.width=e.height+"px",j.style.top=
e.top+n+"px"),n=Math.round((e.height-30)/2),30<e.height&&(j.style.top=e.top+n+"px"));j.className+="teardrop"}}function delete_combo_item(a,c){var b=getComboId(a);if(b=document.getElementById(b))for(var d=getItems(b),e=0;e<d.length;e++)if(d[e].innerHTML==c){for(d.splice(e,1);b.hasChildNodes();)b.removeChild(b.firstChild);for(e=0;e<d.length;e++)addItem(b,d[e].innerHTML,e);break}}
function close_combo(a,c){c||(c=document);var b=getComboId(a);if(b=c.getElementById(b))"block"==b.style.display&&(setStyle(b,"display","none",""),gItemNum=-1),g_do_complete&&unhighlight_combo_all_items(c,a)}function repopulate_combo(a,c,b){b||(b=document);var d=getComboId(a);if(d=b.getElementById(d)){for(;d.hasChildNodes();)d.removeChild(d.firstChild);for(var e=0;e<c.length;e++)addItem(d,c[e],e,b)}a=getComboButtonId(a);(b=b.getElementById(a))&&setStyle(b,"display","","")}
function destroy_combo(a,c){c||(c=document);if(!(null==a||0>=a.length))try{var b=getComboId(a),d=c.getElementById(b);if(d){for(;d.hasChildNodes();)d.removeChild(d.firstChild);d.parentNode.removeChild(d)}var e=getComboButtonId(a),k=c.getElementById(e);k&&k.parentNode.removeChild(k)}catch(h){console.log("destroy_combo error: "+h.message)}}function highlight_combo_item(){return 0}function unhighlight_combo_item(){return 0}function unhighlight_combo_all_items(){return 0}
function getComboId(a){return null===a||""===a?null:a+"_combo"}function getComboButtonId(a){return null===a||""===a?null:a+"_button"}function hide_combo_item(a){null!==a&&setStyle(a,"display","none","")}function show_combo_item(a){null!==a&&setStyle(a,"display","","")}function show_all_combo_items(a,c){a||(a=document);if(!(null==c||0>=c.length)){var b=getComboId(c);if(b=a.getElementById(b))for(var b=getItems(b),d=0;d<b.length;d++)show_combo_item(b[d])}}
function combo_filter(a,c,b){a||(a=document);if(!(null===c||0>=c.length)){var d=!0,e=0;null===b&&(b="");var k=of(b,a),h=null,m=getComboId(c);if(m=a.getElementById(m)){for(var l=getItems(m),f=0;f<l.length;f++){var r="undefined"!=typeof g_isfirefox&&g_isfirefox?l[f].textContent:l[f].innerText;""===b.trim()||0<=r.trim().toLowerCase().indexOf(k.toLowerCase())?(show_combo_item(l[f]),highlight_combo_item(a,c,l[f],b),d=!1,e++,h=l[f]):(hide_combo_item(l[f]),unhighlight_combo_item(a,c,l[f]))}if(d)close_combo(c,
a);else if(b=m.getAttribute("autofilled"),1===e&&"false"==b){m.setAttribute("autofilled","true");if(d=a.getElementById(c))e=d.value.length,b=h.val.length,d.value=h.val,"selectionStart"in d?(d.selectionStart=e,d.selectionEnd=b):(h=d.createTextRange(),h.moveStart("character",e),h.collapse(),h.moveEnd("character",b),h.select());close_combo(c,a)}}}}
function keyupCombo(a,c,b,d){a||(a=document);d=a.getElementById(d);null!==d&&null!==b&&(c=c.keyCode,c==KEY_DOWN||(c==KEY_F4||c==KEY_UP||c==KEY_ENTER||c==KEY_ESCAPE)||(isComboShowing(d)||(showCombo(b,d,null,a),gItemNum=-1,setTimeout(function(){doFocus()},0)),combo_filter(a,b.id,b.value)))}function isComboShowing(a){return null===a?!1:"block"==a.style.display}function insertAfter(a,c){a.parentNode.insertBefore(c,a.nextSibling)};
